targets = [{ triple = "x86_64-unknown-linux-gnu" }, { triple = "aarch64-unknown-linux-gnu" }]

[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0", "MPL-2.0"]
deny = []
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "allow"
confidence-threshold = 0.8
exceptions = []

# Some crates don't have (easily) machine readable licensing information,
# adding a clarification entry for it allows you to manually specify the
# licensing information
#[[licenses.clarify]]
# The name of the crate the clarification applies to
#name = "ring"
# The optional version constraint for the crate
#version = "*"
# The SPDX expression for the license requirements of the crate
#expression = "MIT AND ISC AND OpenSSL"
# One or more files in the crate's source used as the "source of truth" for
# the license expression. If the contents match, the clarification will be used
# when running the license check, otherwise the clarification will be ignored
# and the crate will be checked normally, which may produce warnings or errors
# depending on the rest of your configuration
#license-files = [
# Each entry is a crate relative path, and the (opaque) hash of its contents
#{ path = "LICENSE", hash = 0xbd0eed23 }
#]

[[licenses.clarify]]
name = "libcosmic-widgets"
expression = "MPL-2.0"
license-files = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
allow = []
deny = [{ name = "libadwaita" }, { name = "libadwaita-sys" }]
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/AaronErhardt/relm4"]

[sources.allow-org]
github = ["pop-os"]